name: Create PDF

on:
  push:
    branches:
      - Feature/#18124_autobuild_pdf
      # - main

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install pandoc and texlive
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra
      
      - name: Convert MD to PDF (English)
        run: |
          find docs/en -name "*.md" -type f -print0 | xargs -0 pandoc -o documentation_en.pdf --pdf-engine=xelatex
      
      - name: Convert MD to PDF (Spanish)
        run: |
          find docs/es -name "*.md" -type f -print0 | xargs -0 pandoc -o documentation_es.pdf --pdf-engine=xelatex
      
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v2
        with:
          name: documentation-pdfs
          path: |
            documentation_en.pdf
            documentation_es.pdf