name: Create PDF

on:
  push:
    branches:
      - Feature/#18124_autobuild_pdf
      # - main

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install MkDocs and required plugins
        run: |
          pip install mkdocs mkdocs-material mkdocs-pdf-export-plugin
      
      - name: Build MkDocs site and generate PDF (English)
        run: |
          mkdocs build -f mkdocs.yml
          mv site/pdf/document.pdf documentation_en.pdf

      - name: Build MkDocs site and generate PDF (Spanish)
        run: |
          mkdocs build -f mkdocs.es.yml
          mv site/pdf/document.pdf documentation_es.pdf

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation-pdfs
          path: |
            documentation_en.pdf
            documentation_es.pdf